# NOME DA APLICAÇÃO
spring.application.name=sistema-eventos

# URL DE CONEXÃO COM O BANCO DE DADOS MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_eventos

# USUÁRIO DO BANCO DE DADOS
spring.datasource.username=root

# SENHA DO BANCO DE DADOS
spring.datasource.password=

# ATUALIZA AS TABELAS AUTOMATICAMENTE NO BANCO
spring.jpa.hibernate.ddl-auto=update

# MOSTRA OS COMANDOS SQL NO CONSOLE
spring.jpa.show-sql=true

# FORMATA OS COMANDOS SQL NO CONSOLE
spring.jpa.properties.hibernate.format_sql=true

# DESATIVA O CACHE DO THYMELEAF
spring.thymeleaf.cache=false